version: "3.9"
services:
  dbus:
    build: ./dbus
    image: iuri/venus-dbus
    restart: always
    volumes:
      - "var_run_dbus:/var/run/dbus"
  localsettings:
    build: ./localsettings
    image: iuri/venus-localsettings
    restart: always
    volumes:
      - "var_run_dbus:/var/run/dbus"
      - "data:/data"
  dbus-systemcalc-py:
    build: ./dbus-systemcalc-py
    image: iuri/venus-dbus-systemcalc-py
    restart: always
    volumes:
      - "var_run_dbus:/var/run/dbus"
      - "data:/data"
  vrmlogger:
    build: ./vrmlogger
    image: iuri/venus-vrmlogger
    restart: always
    network_mode: host
    volumes:
      - "var_run_dbus:/var/run/dbus"
      - "data:/data"
  dbus-vebus-to-pvinverter:
    build: ./dbus-vebus-to-pvinverter
    image: iuri/venus-dbus-vebus-to-pvinverter
    restart: always
    volumes:
      - "var_run_dbus:/var/run/dbus"
      - "data:/data"
  mk2-dbus:
    build: ./mk2-dbus
    image: iuri/venus-mk2-dbus
    restart: always
    devices:
      - "/dev/tty0:/dev/ttyS0"
    environment:
      - "MK3DEV=ttyS0"
    volumes:
      - "var_run_dbus:/var/run/dbus"
      - "data:/data"
  vedirect:
    build: ./vedirect
    image: iuri/venus-vedirect
    restart: always
    devices:
      - "/dev/tty0:/dev/ttyUSB0"
    environment:
      - "VEDIRECTDEV=/dev/ttyUSB0"
    volumes:
      - "var_run_dbus:/var/run/dbus"
      - "data:/data"
  dbus-mqtt:
    build: ./dbus-mqtt
    image: iuri/venus-dbus-mqtt
    restart: always
    volumes:
      - "var_run_dbus:/var/run/dbus"
      - "data:/data"
    environment:
      - "MQTT_BROKER_HOST=mosquitto"
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto-config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    restart: always
volumes:
  mosquitto-config:
  mosquitto-data:
  mosquitto-log:
  var_run_dbus:
  data:
